# Generated by Django 4.2.1 on 2023-06-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True, verbose_name='почта'),
        ),
    ]
